# Generated by Django 4.2.7 on 2025-11-01 03:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrimeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("multiplayer", "Multiplayer"),
                            ("organized", "Organized"),
                        ],
                        default="solo",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Difficulty rating on a 1-10 scale.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "base_success_rate",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Base chance of success represented as a percentage.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("base_cash_reward", models.PositiveIntegerField(default=100)),
                ("base_xp_reward", models.PositiveIntegerField(default=10)),
                ("min_level", models.PositiveIntegerField(default=1)),
                (
                    "min_crew_members",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum crew members required (organized crimes).",
                    ),
                ),
                ("cooldown_minutes", models.PositiveIntegerField(default=5)),
                ("jail_time_minutes", models.PositiveIntegerField(default=0)),
                ("hospital_time_minutes", models.PositiveIntegerField(default=0)),
                ("cash_loss_on_fail", models.PositiveIntegerField(default=0)),
                ("flavor_text_success", models.TextField(blank=True, default="")),
                ("flavor_text_failure", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Crime Type",
                "verbose_name_plural": "Crime Types",
                "db_table": "crime_types",
                "ordering": ["category", "difficulty", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="idx_crime_types_slug"),
                    models.Index(fields=["category"], name="idx_crime_types_category"),
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["is_active"],
                        name="idx_crime_types_active",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrimeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("success", models.BooleanField()),
                ("cash_earned", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("items_found", models.JSONField(blank=True, default=list)),
                ("character_level", models.PositiveIntegerField()),
                (
                    "success_rate",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "roll_result",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crime_history",
                        to="core.character",
                    ),
                ),
                (
                    "crime_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="crimes.crimetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crime History Entry",
                "verbose_name_plural": "Crime History",
                "db_table": "crime_history",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="CrimeCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_attempted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("can_attempt_at", models.DateTimeField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crime_cooldowns",
                        to="core.character",
                    ),
                ),
                (
                    "crime_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooldowns",
                        to="crimes.crimetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crime Cooldown",
                "verbose_name_plural": "Crime Cooldowns",
                "db_table": "crime_cooldowns",
            },
        ),
        migrations.CreateModel(
            name="DailyCrimeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("solo_crimes_today", models.PositiveIntegerField(default=0)),
                ("multiplayer_crimes_today", models.PositiveIntegerField(default=0)),
                ("organized_crimes_today", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_crime_counts",
                        to="core.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Crime Count",
                "verbose_name_plural": "Daily Crime Counts",
                "db_table": "daily_crime_counts",
                "indexes": [
                    models.Index(
                        fields=["character", "date"],
                        name="idx_daily_crime_counts_character_date",
                    ),
                    models.Index(fields=["date"], name="idx_daily_crime_counts_date"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailycrimecount",
            constraint=models.UniqueConstraint(
                fields=("character", "date"),
                name="uniq_daily_crime_counts_character_date",
            ),
        ),
        migrations.AddIndex(
            model_name="crimehistory",
            index=models.Index(
                fields=["character"], name="idx_crime_history_character"
            ),
        ),
        migrations.AddIndex(
            model_name="crimehistory",
            index=models.Index(fields=["crime_type"], name="idx_crime_history_type"),
        ),
        migrations.AddIndex(
            model_name="crimehistory",
            index=models.Index(
                fields=["attempted_at"], name="idx_crime_history_attempted_at"
            ),
        ),
        migrations.AddIndex(
            model_name="crimehistory",
            index=models.Index(fields=["success"], name="idx_crime_history_success"),
        ),
        migrations.AddIndex(
            model_name="crimehistory",
            index=models.Index(
                fields=["character", "attempted_at"],
                name="idx_crime_history_character_date",
            ),
        ),
        migrations.AddIndex(
            model_name="crimecooldown",
            index=models.Index(
                fields=["character"], name="idx_crime_cooldowns_character"
            ),
        ),
        migrations.AddIndex(
            model_name="crimecooldown",
            index=models.Index(
                fields=["can_attempt_at"], name="idx_crime_cooldowns_available"
            ),
        ),
        migrations.AddIndex(
            model_name="crimecooldown",
            index=models.Index(
                fields=["character", "can_attempt_at"],
                name="idx_crime_cooldowns_character_available",
            ),
        ),
        migrations.AddConstraint(
            model_name="crimecooldown",
            constraint=models.UniqueConstraint(
                fields=("character", "crime_type"),
                name="uniq_crime_cooldown_character_type",
            ),
        ),
    ]
